networks:
  lan:
    driver: bridge

include:
  - path: ./apps/jellyfin/docker-compose.yml
  - path: ./apps/minecraft/docker-compose.yml
  - path: ./apps/homeassistant/docker-compose.yml
  - path: ./apps/chatpardy/docker-compose.yml
  - path: ./apps/actualbudget/docker-compose.yml
