services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles # e.g., "America/New_York"
    volumes:
      - "${HOME_ASSISTANT_CONFIG}:/config"
      - /run/dbus:/run/dbus:ro
    env_file:
      - path: .env
        required: true
    ports:
      # this is the default but setting this here for clarity
      - "8123:8123"
