services:
  chatpardy:
    image: ghcr.io/johncmanuel/chatpardy:latest
    restart: unless-stopped
    container_name: chatpardy
    user: "${UID}:${GID}"
    volumes:
      - "${CHATPARDY_DB_PATH}:/app/Database"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
